version: "3"

services:
  kgalleryapi:
    build:
      context: .
    volumes:
      - ./:/app
    container_name: kgallery-api
    ports:
      - "3000:3000"
    networks:
      - kgallery
  kgallerydb:
    image: postgres:15
    environment:
      - PGHOST=postgres
      - POSTGRES_PASSWORD=root
      - POSTGRES_DB=root
    volumes:
      - ./postgres:/data/postgres
    ports:
      - "5432:5432"
    expose:
      - 5432
    networks:
      - kgallery
networks:
  kgallery:
    driver: bridge
