name: Server test

on:
  push:
    branches-ignore:
      - "main"
jobs:
  test:
    runs-on: ubuntu-latest
    timeout-minutes: 15
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v3
        with:
          node-version: "16.15"
      - run: yarn
      - run: yarn test
